"""Running the Alembic migrations from inside the application.

``DatabaseStore`` used to call ``Base.metadata.create_all``, which only ever
creates missing tables and never changes one that already exists. It now brings
its database up to the latest revision instead, so a schema change reaches a
``piano.db`` that already has rows in it.

The connection handling here is the load-bearing part. The test suite pins
``sqlite+pysqlite:///:memory:``, whose database lives inside a single connection
held open by ``StaticPool`` (``backend/database.py``). A second connection to
that URL is a second, empty database, so the migrations have to run on the
engine the store already uses -- never on a freshly built one.
"""

from __future__ import annotations

from pathlib import Path

from alembic import command
from alembic.config import Config
from alembic.migration import MigrationContext
from alembic.script import ScriptDirectory
from sqlalchemy import Connection, inspect
from sqlalchemy.engine import Engine

from .database import Base


BACKEND_DIR = Path(__file__).resolve().parent
ALEMBIC_INI = BACKEND_DIR / "alembic.ini"
MIGRATIONS_DIR = BACKEND_DIR / "migrations"

VERSION_TABLE = "alembic_version"

# Options every migration run is configured with, shared with migrations/env.py.
#
# render_as_batch is required rather than a nicety: SQLite cannot ALTER TABLE for
# most column and constraint changes, so without batch mode an autogenerated
# "add a column" migration would be unrunnable on the only database this project
# has.
MIGRATION_CONTEXT_OPTIONS: dict[str, object] = {
    "render_as_batch": True,
    "compare_type": True,
    "compare_server_default": True,
}


def alembic_config(connection: Connection | None = None) -> Config:
    """The project's Alembic config, optionally bound to a live connection.

    When ``connection`` is given, ``env.py`` runs the migrations on it instead of
    opening its own.
    """
    config = Config(str(ALEMBIC_INI))
    config.set_main_option("script_location", str(MIGRATIONS_DIR))
    if connection is not None:
        config.attributes["connection"] = connection
    return config


def head_revision() -> str:
    """The revision every database is expected to end up at."""
    return ScriptDirectory.from_config(alembic_config()).get_current_head()


def base_revision() -> str:
    """The first revision in the history, used to adopt pre-Alembic databases."""
    script = ScriptDirectory.from_config(alembic_config())
    return script.get_base()


def current_revision(connection: Connection) -> str | None:
    return MigrationContext.configure(connection).get_current_revision()


def _is_pre_alembic_database(connection: Connection) -> bool:
    """True for a database built by the old ``create_all`` code.

    Such a database has the initial schema but no version table, so running the
    initial revision against it would fail on an existing table. It is stamped
    with the initial revision instead and then upgraded from there.
    """
    table_names = set(inspect(connection).get_table_names())
    if VERSION_TABLE in table_names:
        return False
    return any(table.name in table_names for table in Base.metadata.sorted_tables)


def upgrade_to_head(engine: Engine) -> None:
    """Bring ``engine``'s database up to the latest revision, on its connection."""
    with engine.begin() as connection:
        config = alembic_config(connection)
        if _is_pre_alembic_database(connection):
            command.stamp(config, base_revision())
        command.upgrade(config, "head")


def downgrade_to_base(engine: Engine) -> None:
    """Unwind every revision, leaving an empty database. Used by the test reset."""
    with engine.begin() as connection:
        command.downgrade(alembic_config(connection), "base")
