"""Schema tests for the Alembic migrations.

Like `tests/test_database.py`, these go at the persistence layer directly rather
than through an HTTP endpoint: there is no endpoint for "the schema is correct".
"""

import os
import shutil
import subprocess
from pathlib import Path

from alembic import command
from alembic.autogenerate import compare_metadata
from alembic.migration import MigrationContext
from sqlalchemy import text
from sqlalchemy.engine import Engine

from backend.database import Base, create_database_engine, create_session_factory
from backend.db_models import PackageRecord, StudentRecord, TeacherSettingsRecord
from backend.migrator import (
    MIGRATION_CONTEXT_OPTIONS,
    MIGRATIONS_DIR,
    VERSION_TABLE,
    alembic_config,
    current_revision,
    downgrade_to_base,
    head_revision,
    upgrade_to_head,
)
from backend.store import DatabaseStore


REPO_ROOT = Path(__file__).resolve().parents[1]


def _schema(engine: Engine) -> set[tuple[str, str, str, str]]:
    """Every table, index and trigger SQLite holds, minus Alembic's bookkeeping."""
    with engine.connect() as connection:
        rows = connection.execute(
            text("SELECT type, name, tbl_name, sql FROM sqlite_master")
        ).all()
    return {
        (row[0], row[1], row[2], " ".join((row[3] or "").split()))
        for row in rows
        if row[2] != VERSION_TABLE
    }


def _table_names(engine: Engine) -> set[str]:
    return {name for kind, name, _, _ in _schema(engine) if kind == "table"}


def test_initial_revision_reproduces_the_create_all_schema() -> None:
    from_create_all = create_database_engine("sqlite+pysqlite:///:memory:")
    Base.metadata.create_all(from_create_all)

    from_migrations = create_database_engine("sqlite+pysqlite:///:memory:")
    upgrade_to_head(from_migrations)

    assert _schema(from_migrations) == _schema(from_create_all)
    from_create_all.dispose()
    from_migrations.dispose()


def test_migrations_round_trip_leaves_the_same_schema(tmp_path) -> None:
    engine = create_database_engine(f"sqlite+pysqlite:///{tmp_path / 'round-trip.db'}")
    upgrade_to_head(engine)
    after_first_upgrade = _schema(engine)

    downgrade_to_base(engine)
    after_downgrade = _table_names(engine)

    upgrade_to_head(engine)
    after_second_upgrade = _schema(engine)

    assert len(after_first_upgrade) > 0
    assert after_downgrade == set()
    assert after_second_upgrade == after_first_upgrade
    engine.dispose()


def test_migrated_schema_matches_the_models() -> None:
    engine = create_database_engine("sqlite+pysqlite:///:memory:")
    upgrade_to_head(engine)

    with engine.connect() as connection:
        context = MigrationContext.configure(
            connection,
            opts={"target_metadata": Base.metadata, **MIGRATION_CONTEXT_OPTIONS},
        )
        differences = compare_metadata(context, Base.metadata)

    assert differences == []
    engine.dispose()


def test_autogenerated_migrations_use_batch_mode_for_sqlite(tmp_path) -> None:
    """SQLite cannot ALTER TABLE without batch mode, so env.py must render it."""
    engine = create_database_engine(f"sqlite+pysqlite:///{tmp_path / 'batch.db'}")
    upgrade_to_head(engine)
    scripts = tmp_path / "migrations"
    shutil.copytree(MIGRATIONS_DIR, scripts)

    with engine.begin() as connection:
        connection.execute(text("ALTER TABLE students DROP COLUMN slot_time"))
    with engine.begin() as connection:
        config = alembic_config(connection)
        config.set_main_option("script_location", str(scripts))
        script = command.revision(config, message="batch probe", autogenerate=True)

    generated = Path(script.path).read_text()

    assert "with op.batch_alter_table('students'" in generated
    assert "batch_op.add_column(sa.Column('slot_time'" in generated
    engine.dispose()


def test_store_migrates_the_in_memory_database_it_holds_open() -> None:
    """StaticPool keeps the in-memory database in one connection: it must be the
    connection the migrations run on, or the store would see an empty schema."""
    store = DatabaseStore("sqlite+pysqlite:///:memory:")

    with store.engine.connect() as connection:
        revision = current_revision(connection)

    assert revision == head_revision()
    assert _table_names(store.engine) == {table.name for table in Base.metadata.sorted_tables}
    assert store.student_for_token("anna").name == "Anna Lie"
    store.engine.dispose()


def test_store_brings_a_fresh_file_database_to_head(tmp_path) -> None:
    store = DatabaseStore(f"sqlite+pysqlite:///{tmp_path / 'fresh.db'}")

    with store.engine.connect() as connection:
        revision = current_revision(connection)

    assert revision == head_revision()
    assert _table_names(store.engine) == {table.name for table in Base.metadata.sorted_tables}
    store.engine.dispose()


def test_store_adopts_a_database_built_before_migrations_existed(tmp_path) -> None:
    """A `piano.db` from the create_all days has the schema but no version table.

    It is stamped with the initial revision and upgraded from there, instead of
    failing on tables that already exist or being reseeded from scratch.
    """
    url = f"sqlite+pysqlite:///{tmp_path / 'legacy.db'}"
    legacy_engine = create_database_engine(url)
    Base.metadata.create_all(legacy_engine)
    with create_session_factory(legacy_engine).begin() as session:
        session.add(
            TeacherSettingsRecord(
                id=1, username="admin", password_hash="not-a-real-hash", timezone="Europe/Oslo"
            )
        )
        session.add(
            StudentRecord(
                id=1,
                name="Legacy Student",
                status="active",
                token="legacy",
                slot_day=2,
                slot_time="16:15",
            )
        )
        session.flush()
        session.add(PackageRecord(student_id=1, size=10, used=3, period_no=1, invoice_sent=False))
    legacy_engine.dispose()

    store = DatabaseStore(url)
    with store.engine.connect() as connection:
        revision = current_revision(connection)

    assert revision == head_revision()
    assert store.student_for_token("legacy").name == "Legacy Student"
    assert list(store.students) == [1]
    store.engine.dispose()


def test_migrate_target_upgrades_the_configured_database(tmp_path) -> None:
    """`make migrate` reads PIANO_DATABASE_URL exactly as the application does."""
    database = tmp_path / "cli.db"
    result = subprocess.run(
        ["make", "migrate"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        env={**os.environ, "PIANO_DATABASE_URL": f"sqlite+pysqlite:///{database}"},
    )
    engine = create_database_engine(f"sqlite+pysqlite:///{database}")
    with engine.connect() as connection:
        revision = current_revision(connection)

    assert result.returncode == 0, result.stderr
    assert database.exists()
    assert revision == head_revision()
    assert _table_names(engine) == {table.name for table in Base.metadata.sorted_tables}
    engine.dispose()
